// export const GET_ALL_SETTINGS = 'GET_ALL_SETTINGS';
// export const GET_ONE_SETTING = 'GET_ONE_SETTING';

export const GET_ALL_ELEMENTS = 'GET_ALL_ELEMENTS';
export const SET_CURRENT_PROMPT = 'SET_CURRENT_PROMPT';

export const SAVE_PROMPT = 'SAVE_PROMPT';
export const GET_ALL_SAVED_PROMPTS = 'GET_ALL_SAVED_PROMPTS';

export const UPDATE_USER = 'UPDATE_USER';
