export const settingData = [
  'Outside an abandoned warehouse',
  'At vacation home in upstate New York',
  'On a beach',
  'Inside a stalled commuter train',
  'At the ballet',
  'On a romatic trip',
  'Hiding under a piece of furniture',
  'On a first date',
  'During a monsoon',
  'In gridlocked traffic',
  'In the backseat of an Uber',
  'While boarding an airplane',
  'During an intense snowstorm',
  'Under a famous bridge',
  'On an Alaskan cruise',
  'At a crowded campsite',
  'In Florida',
  'In the woods',
  'Outside of a beauty salon',
  'In the parking lot of an old shopping center',
  'At a wedding reception',
  'At an upscale party',
  'On a fishing boat',
  'On a long-anticipated trip',
  'In a restaurant without air-conditioning',
  'At an aging amusement park',
  "Outside a therapist's office",
  'At a fast food restaurant',
  'In a cramped kitchen',
  "In a stranger's home",
  'At a convention',
  'At a brand new office park',
  'In a packed movie theater',
  "At the premier of a rival's movie",
  'At a rest stop outside their hometown',
  'At an in-laws house',
  'In a graveyard at dusk',
  'While visiting a national park',
  'At a bar owned by their abuser',
  'Outside of their condemned childhood home',
  'In a sketchy AirBnB',
  'In a haunted hotel',
  'On their first day',
  'At a support group',
  'In court-ordered group therapy',
  "During a loved one's contentious trial",
  'At a concert they were forced to attend',
  'At the school reunion they co-planned',
  'At a family reunion on the hottest day of the year',
  'At an auction',
  "At a place that doesn't exist anymore",
  "At a child's birthday party",
  'At the funeral of an estranged family member',
  'At a defunct summer camp',
  'Inside the belly of a whale',
  'Under a blood moon',
  'During a meteor shower',
  'During a shooting',
  'At the last roller rink in town',
  'On the final night at a beloved venue',
  'At a video game tournament',
  'In an empty condo',
  'At timeshare presentation',
  'At a high school prom',
  'At their elementary school playground'
];

export const adjectiveData = [
  'mean',
  'kind',
  'retired',
  'hopeless',
  'athletic',
  'arrogant',
  'insecure',
  'rude',
  'lost',
  'scared',
  'nervous',
  'overly friendly',
  'creepy',
  'wealthy',
  'broke',
  'talented',
  'deranged',
  'unhealthy',
  'anxious',
  'impatient',
  'gentle',
  'novice',
  'pedantic',
  'abusive',
  'tall',
  'awkward',
  'dubious',
  'exhausted',
  'vain',
  'unfaithful',
  'lonely',
  'unpopular',
  'popular',
  'agoraphobic',
  'jealous',
  'secretive',
  'ashamed',
  'unemployed',
  'ugly',
  'homeless',
  'divorced',
  'insincere',
  'possessive',
  'untrustworthy',
  'passive',
  'aggressive',
  'manipulative',
  'earnest',
  'psychic',
  'haunted',
  'petty',
  'materialistic',
  'famous',
  'sweet',
  'out-of-place',
  'isolated',
  'wacky',
  'spoiled',
  'sneaky',
  'proud',
  'irresponsible',
  'depressed',
  'sentimenal',
  'unsentimental',
  'obsessed',
  'dishonest',
  'unreliable'
];

export const mainCharacterData = [
  'teenage boy',
  'middle-aged woman',
  'dancer',
  'drunk',
  'romantic',
  'teacher',
  'idiot',
  'student',
  'high-powered executive',
  'software engineer',
  'graphic designer',
  'painter',
  'electrician',
  'poet',
  'dog trainer',
  'teenage girl',
  'middle-aged man',
  'grandmother',
  'grandfather',
  'security guard',
  'musician',
  'valet',
  'tourist',
  'postal worker',
  'baby sitter',
  'server',
  'actor',
  'TV personality',
  'therapist',
  'skydiver',
  'truck driver',
  'fashion blogger',
  'magician',
  'social media celebrity',
  'pilot',
  'farmer',
  'standup comic',
  'lottery winner',
  'scientist',
  'nurse',
  'gynecologist',
  'dentist',
  'dental hygenist',
  'bus driver',
  'snow boarder',
  'exotic dancer',
  'sex worker',
  'makeup artist',
  'felon',
  'lawyer',
  'CEO',
  'hunter',
  'writer',
  'cashier',
  'delivery driver',
  'real estate agent',
  'cook',
  'nail technician',
  'politician',
  'choreographer',
  'singer',
  'bartender',
  'tutor',
  'assistant',
  'scammer'
];

export const detailData = [
  'who walks with a limp',
  'whose cancer is in remission',
  'who owns two Corgis',
  'who tries to hide a subtle tic',
  'who enjoys stealing',
  'who brags about giving to charity',
  'who runs marathons',
  'who once stalked an ex',
  'who donated a kidney to a friend',
  'who once tried to kidnap a baby',
  'who runs an infamous social media account',
  'who collects antique dishware',
  'who used to be famous',
  'who has OCD',
  "who dreams of running an artists' commune",
  'who longs to get rich',
  'who understands several languages',
  'who wants to go back to school',
  'who uses a wheelchair',
  'who sells pictures of their feet',
  'who has an eating disorder',
  'who hides their smoking habit',
  'who feels embarrassed about their cystic acne',
  'who runs an unpopular meetup group',
  "who doesn't have any friends",
  'who recently came into an inheritance',
  'who is terrified of driving',
  'who gave their child up for adoption',
  "who hasn't cried in ten years",
  "who can't speak the language",
  'who loves to play the hero',
  'who has just fallen in love',
  'who has a secret family',
  'who just moved to the area',
  'who pines for a suicidal ex',
  'who plans to propose',
  'who daydreams about faking their own death',
  'who only wears cat-themed clothes',
  "who can't stop doing inappropriate bits",
  'whose child died in a tragic accident',
  'who has a bird phobia',
  'who believes in demonic possession',
  'who stabbed someone while high',
  'who survived a plane crash',
  'who is terrible at lying',
  'who is addicted to gambling',
  'who accidentally killed a child a long time ago',
  'who is very into prescribed gender roles',
  'who found religion',
  "who didn't do it",
  'whose identical sibling stole their identity',
  'who has the same name as an infamous celebrity',
  'who never does the things they say they will',
  'who was raised by their grandparents',
  'who recently broke a leg',
  'who has tremendous credit card debt',
  'who has a shady side hustle',
  'who plans flash mobs in their spare time',
  'who is a compulsive liar',
  'who was just diagnosed with a terminal illness',
  'who has regular night terrors',
  'who hates breaking the rules',
  'who has severe misophonia',
  'who speaks very loudly',
  'who has a failing memory'
];

export const risingActionData = [
  'forgets an important date',
  'misplaces a ticket',
  'takes a poorly timed photo',
  'bullies a student online',
  'tells a lie about their family',
  'fakes an illness',
  'gets a terrible haircut ',
  'learns a huge secret',
  'googles an estranged parent',
  'runs into an ex',
  'prepares for an important meeting',
  'breaks up with their partner',
  'discovers they have lice',
  'buys an expensive pet',
  'gets drunk during the day',
  'plays an instrument badly',
  'bombs an interview',
  'asks for advice online',
  'tries to return a purchase after the deadline',
  'finds something hidden in the walls',
  'eats expired food',
  'finds a dead body',
  'deletes a message meant for someone else',
  'receives an exciting call',
  'receives bad news',
  'buys a round for the wrong person',
  'buys a lottery ticket',
  'cheats a stranger ',
  'cheats on their partner',
  'leaves their kid in the car',
  'draws a crude picture',
  'says something stupid in front of someone they admire',
  'takes in a stray',
  'quits the job they love',
  'makes an impulse purchase',
  'slams their hand in a door',
  'starts a rumor',
  "steals a child's toy",
  'runs out of cash',
  'receives a strange message from an acquaintance',
  'argues with a telemarketer',
  'blames a coworker for their mistake',
  'ignores a sick pet',
  'writes a vindictive review',
  "breaks into an enemy's apartment",
  "spills wine on a stranger's laptop",
  'gets stuck in a bathroom stall',
  'comes up with a crazy plan',
  'robs a convenience store',
  'prepares for an approaching storm',
  'plans to steal an inheritance',
  'leaves their diary where friends and family can find it',
  "reads a loved one's diary",
  'accuses a former teacher of impropriety',
  'gives their financial information to a scammer',
  'paints their home an unfortunate color',
  'interrupts a speech',
  'begins to catfish an acquaintance ',
  "discovers their partner isn't who they say they are",
  'pretends to be someone else',
  'falls from a horse',
  'hits their head doing something foolish',
  'tries to pass off a fake as the real thing',
  'confesses a crush to an uninterested person',
  "frees caged animals that don't belong to them"
];

const rawclimaxData = [
  'and gets caught stealing.',
  'and loses a prized possession.',
  'and reveals a huge secret.',
  'and hits a pedestrian with their car.',
  'and destroys a prized possession.',
  'and finds a long-lost item.',
  'and wins a prize.',
  'and crashes a bike.',
  'and performs before an uneasy crowd.',
  'and makes a dreaded phone call.',
  'and throws up in public.',
  'and gets hit by a cyclist.',
  'and falls into a fountain. ',
  'and breaks a promise.',
  'and dislocates their shoulder.',
  'and accidentally knocks over a child.',
  'and makes a scene. ',
  'and lashes out at an innocent bystander.',
  'and ruins a bachelorette party.',
  'and flies an airplane.',
  "and learns of an acquaintance's death.",
  'and stands up to their father.',
  'and remembers something important too late.',
  'and abandons their car.',
  'and watches their home as it burns. ',
  'and slaps their neighbor.',
  'and starts sobbing at an unexpected sight.',
  'and gets called a name by someone they love. ',
  'and loses a bet. ',
  'and kills a small animal.',
  'and confonts their childhood bully. ',
  'and breaks a window. ',
  'and gets robbed by preteens.',
  "and opens a dead relative's storage unit.",
  'and visits a psychic.',
  'and confronts a prophet. ',
  "and gets fired for something they didn't do. ",
  'and witnesses a crime.',
  'and gets stranded on the highway.',
  'and hires a hot air balloon pilot.',
  "and takes a psychic's advice. ",
  'and learns that they were wrong.',
  'and decides not to sign an important document.',
  'and gets caught watching porn on their phone. ',
  'and accidentally clicks send on a nasty email draft.',
  'and gets locked out. ',
  'and has a premonition that comes true.',
  'and refuses to forgive the person who wronged them.',
  'and asks for forgiveness from someone who cannot give it.',
  'and gets caught in a hail storm.',
  'and hides from a former friend.',
  'and decides to tell the truth.',
  'and refuses to change their mind.',
  'and demands a refund.',
  'and declares someone a fraud.',
  'and presents someone with an unexpected gift.',
  'and feels the aftershock of an earthquake.',
  'and gets shot.',
  'and reveals a hidden identity.',
  'and crashes a party.',
  "and can't find their car.",
  'and sends a company-wide email.',
  'and takes back a gift.',
  'and joins a horde.',
  'and starts a riot. '
];

export const climaxData = rawclimaxData.map(string => {
  let period = string.indexOf('.');
  return string.substring(4, period);
});
